### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by dholth** [conda/conda-package-streaming#84]
### Summary

Placeholder for `conda-package-streaming YY.M.x` release.

| Pilot | dholth |
|---|---|
| Co-pilot | jezdez |

### Tasks

[milestone]: https://github.com/conda/conda-package-streaming/milestone/<milestone>
[process]: https://github.com/conda/conda-package-streaming/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-package-streaming/releases
[main]: https://github.com/AnacondaRecipes/conda-package-streaming-feedstock
[conda-forge]: https://github.com/conda-forge/conda-package-streaming-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-package-streaming/

<details open>  
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `YY.M.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-package-streaming-YY.M.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process])
- [x] [Publish release][releases]
- [x] Merge `YY.M.x` back into `main`
- [x] Activate the `YY.M.x` branch on [ReadTheDocs][ReadTheDocs]
- [ ] Feedstocks
    - [ ] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main]
    - [ ] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge]
    
- [ ] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

**Comment by dholth** [comment]
This is a simpler project than conda and will not use all release steps.

**Comment by jaimergp** [comment]
In conda-forge: https://github.com/conda-forge/conda-package-streaming-feedstock/pull/9

**Comment by dholth** [comment]
Completed
